// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: grpc/pb/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int64                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	NumReviews    int64                  `protobuf:"varint,7,opt,name=num_reviews,json=numReviews,proto3" json:"num_reviews,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int64                  `protobuf:"varint,9,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReq) Reset() {
	*x = ProductReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReq) ProtoMessage() {}

func (x *ProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReq.ProtoReflect.Descriptor instead.
func (*ProductReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductReq) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductReq) GetNumReviews() int64 {
	if x != nil {
		return x.NumReviews
	}
	return 0
}

func (x *ProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductReq) GetCountInStock() int64 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

type ProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int64                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	NumReviews    int64                  `protobuf:"varint,7,opt,name=num_reviews,json=numReviews,proto3" json:"num_reviews,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int64                  `protobuf:"varint,9,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRes) Reset() {
	*x = ProductRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRes) ProtoMessage() {}

func (x *ProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRes.ProtoReflect.Descriptor instead.
func (*ProductRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductRes) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductRes) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductRes) GetNumReviews() int64 {
	if x != nil {
		return x.NumReviews
	}
	return 0
}

func (x *ProductRes) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductRes) GetCountInStock() int64 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *ProductRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductRes          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductRes) Reset() {
	*x = ListProductRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRes) ProtoMessage() {}

func (x *ListProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRes.ProtoReflect.Descriptor instead.
func (*ListProductRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductRes) GetProducts() []*ProductRes {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ProductId     int64                  `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_grpc_pb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TaxPrice      float64                `protobuf:"fixed64,4,opt,name=tax_price,json=taxPrice,proto3" json:"tax_price,omitempty"`
	ShippingPrice float64                `protobuf:"fixed64,5,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{4}
}

func (x *OrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderReq) GetTaxPrice() float64 {
	if x != nil {
		return x.TaxPrice
	}
	return 0
}

func (x *OrderReq) GetShippingPrice() float64 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *OrderReq) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TaxPrice      float64                `protobuf:"fixed64,4,opt,name=tax_price,json=taxPrice,proto3" json:"tax_price,omitempty"`
	ShippingPrice float64                `protobuf:"fixed64,5,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{5}
}

func (x *OrderRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRes) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderRes) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderRes) GetTaxPrice() float64 {
	if x != nil {
		return x.TaxPrice
	}
	return 0
}

func (x *OrderRes) GetShippingPrice() float64 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *OrderRes) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderRes            `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRes) Reset() {
	*x = ListOrderRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRes) ProtoMessage() {}

func (x *ListOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRes.ProtoReflect.Descriptor instead.
func (*ListOrderRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrderRes) GetOrders() []*OrderRes {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{7}
}

func (x *UserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type UserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRes) Reset() {
	*x = UserRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRes) ProtoMessage() {}

func (x *UserRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRes.ProtoReflect.Descriptor instead.
func (*UserRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{8}
}

func (x *UserRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRes) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserRes             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRes) Reset() {
	*x = ListUserRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRes) ProtoMessage() {}

func (x *ListUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRes.ProtoReflect.Descriptor instead.
func (*ListUserRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserRes) GetUsers() []*UserRes {
	if x != nil {
		return x.Users
	}
	return nil
}

type SessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReq) Reset() {
	*x = SessionReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReq) ProtoMessage() {}

func (x *SessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReq.ProtoReflect.Descriptor instead.
func (*SessionReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{10}
}

func (x *SessionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionReq) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionReq) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SessionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRes) Reset() {
	*x = SessionRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRes) ProtoMessage() {}

func (x *SessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRes.ProtoReflect.Descriptor instead.
func (*SessionRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{11}
}

func (x *SessionRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRes) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionRes) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionRes) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// passwords are only ever sent inbound; credential checks happen on the server
type LoginUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserReq) Reset() {
	*x = LoginUserReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserReq) ProtoMessage() {}

func (x *LoginUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserReq.ProtoReflect.Descriptor instead.
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{12}
}

func (x *LoginUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRes struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	User                  *UserRes               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId             string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken           string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoginUserRes) Reset() {
	*x = LoginUserRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRes) ProtoMessage() {}

func (x *LoginUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRes.ProtoReflect.Descriptor instead.
func (*LoginUserRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{13}
}

func (x *LoginUserRes) GetUser() *UserRes {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginUserRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginUserRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginUserRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginUserRes) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *LoginUserRes) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

type RenewAccessTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAccessTokenReq) Reset() {
	*x = RenewAccessTokenReq{}
	mi := &file_grpc_pb_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAccessTokenReq) ProtoMessage() {}

func (x *RenewAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAccessTokenReq.ProtoReflect.Descriptor instead.
func (*RenewAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{14}
}

func (x *RenewAccessTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RenewAccessTokenRes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccessToken          string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RenewAccessTokenRes) Reset() {
	*x = RenewAccessTokenRes{}
	mi := &file_grpc_pb_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAccessTokenRes) ProtoMessage() {}

func (x *RenewAccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAccessTokenRes.ProtoReflect.Descriptor instead.
func (*RenewAccessTokenRes) Descriptor() ([]byte, []int) {
	return file_grpc_pb_api_proto_rawDescGZIP(), []int{15}
}

func (x *RenewAccessTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RenewAccessTokenRes) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

var File_grpc_pb_api_proto protoreflect.FileDescriptor

const file_grpc_pb_api_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/pb/api.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\n" +
	"ProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x03R\x06rating\x12\x1f\n" +
	"\vnum_reviews\x18\a \x01(\x03R\n" +
	"numReviews\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\t \x01(\x03R\fcountInStock\"\xef\x02\n" +
	"\n" +
	"ProductRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x03R\x06rating\x12\x1f\n" +
	"\vnum_reviews\x18\a \x01(\x03R\n" +
	"numReviews\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\t \x01(\x03R\fcountInStock\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"<\n" +
	"\x0eListProductRes\x12*\n" +
	"\bproducts\x18\x01 \x03(\v2\x0e.pb.ProductResR\bproducts\"\xb1\x01\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"product_id\x18\x06 \x01(\x03R\tproductId\x12\x19\n" +
	"\border_id\x18\a \x01(\x03R\aorderId\"\xe4\x01\n" +
	"\bOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.pb.OrderItemR\x05items\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\ttax_price\x18\x04 \x01(\x01R\btaxPrice\x12%\n" +
	"\x0eshipping_price\x18\x05 \x01(\x01R\rshippingPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x01R\n" +
	"totalPrice\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\"\xda\x02\n" +
	"\bOrderRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.pb.OrderItemR\x05items\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\ttax_price\x18\x04 \x01(\x01R\btaxPrice\x12%\n" +
	"\x0eshipping_price\x18\x05 \x01(\x01R\rshippingPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x01R\n" +
	"totalPrice\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\fListOrderRes\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.pb.OrderResR\x06orders\"z\n" +
	"\aUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\"\xd4\x01\n" +
	"\aUserRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"0\n" +
	"\vListUserRes\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.pb.UserResR\x05users\"\xba\x01\n" +
	"\n" +
	"SessionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xf5\x01\n" +
	"\n" +
	"SessionRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"@\n" +
	"\fLoginUserReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbe\x02\n" +
	"\fLoginUserRes\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.pb.UserResR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAt\":\n" +
	"\x13RenewAccessTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x8b\x01\n" +
	"\x13RenewAccessTokenRes\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt2\xd0\a\n" +
	"\x05Ecomm\x121\n" +
	"\rCreateProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x12.\n" +
	"\n" +
	"GetProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x124\n" +
	"\fListProducts\x12\x0e.pb.ProductReq\x1a\x12.pb.ListProductRes\"\x00\x121\n" +
	"\rUpdateProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x121\n" +
	"\rDeleteProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x12+\n" +
	"\vCreateOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12(\n" +
	"\bGetOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12.\n" +
	"\n" +
	"ListOrders\x12\f.pb.OrderReq\x1a\x10.pb.ListOrderRes\"\x00\x12+\n" +
	"\vDeleteOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12(\n" +
	"\n" +
	"CreateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12%\n" +
	"\aGetUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12+\n" +
	"\tListUsers\x12\v.pb.UserReq\x1a\x0f.pb.ListUserRes\"\x00\x12(\n" +
	"\n" +
	"UpdateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12(\n" +
	"\n" +
	"DeleteUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x121\n" +
	"\rCreateSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x12.\n" +
	"\n" +
	"GetSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rRevokeSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rDeleteSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\tLoginUser\x12\x10.pb.LoginUserReq\x1a\x10.pb.LoginUserRes\"\x00\x12F\n" +
	"\x10RenewAccessToken\x12\x17.pb.RenewAccessTokenReq\x1a\x17.pb.RenewAccessTokenRes\"\x00B&Z$github.com/eunice99x/goMicro/grpc/pbb\x06proto3"

var (
	file_grpc_pb_api_proto_rawDescOnce sync.Once
	file_grpc_pb_api_proto_rawDescData []byte
)

func file_grpc_pb_api_proto_rawDescGZIP() []byte {
	file_grpc_pb_api_proto_rawDescOnce.Do(func() {
		file_grpc_pb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_pb_api_proto_rawDesc), len(file_grpc_pb_api_proto_rawDesc)))
	})
	return file_grpc_pb_api_proto_rawDescData
}

var file_grpc_pb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_grpc_pb_api_proto_goTypes = []any{
	(*ProductReq)(nil),            // 0: pb.ProductReq
	(*ProductRes)(nil),            // 1: pb.ProductRes
	(*ListProductRes)(nil),        // 2: pb.ListProductRes
	(*OrderItem)(nil),             // 3: pb.OrderItem
	(*OrderReq)(nil),              // 4: pb.OrderReq
	(*OrderRes)(nil),              // 5: pb.OrderRes
	(*ListOrderRes)(nil),          // 6: pb.ListOrderRes
	(*UserReq)(nil),               // 7: pb.UserReq
	(*UserRes)(nil),               // 8: pb.UserRes
	(*ListUserRes)(nil),           // 9: pb.ListUserRes
	(*SessionReq)(nil),            // 10: pb.SessionReq
	(*SessionRes)(nil),            // 11: pb.SessionRes
	(*LoginUserReq)(nil),          // 12: pb.LoginUserReq
	(*LoginUserRes)(nil),          // 13: pb.LoginUserRes
	(*RenewAccessTokenReq)(nil),   // 14: pb.RenewAccessTokenReq
	(*RenewAccessTokenRes)(nil),   // 15: pb.RenewAccessTokenRes
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_grpc_pb_api_proto_depIdxs = []int32{
	16, // 0: pb.ProductRes.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: pb.ProductRes.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: pb.ListProductRes.products:type_name -> pb.ProductRes
	3,  // 3: pb.OrderReq.items:type_name -> pb.OrderItem
	3,  // 4: pb.OrderRes.items:type_name -> pb.OrderItem
	16, // 5: pb.OrderRes.created_at:type_name -> google.protobuf.Timestamp
	16, // 6: pb.OrderRes.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: pb.ListOrderRes.orders:type_name -> pb.OrderRes
	16, // 8: pb.UserRes.created_at:type_name -> google.protobuf.Timestamp
	16, // 9: pb.UserRes.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 10: pb.ListUserRes.users:type_name -> pb.UserRes
	16, // 11: pb.SessionReq.expires_at:type_name -> google.protobuf.Timestamp
	16, // 12: pb.SessionRes.created_at:type_name -> google.protobuf.Timestamp
	16, // 13: pb.SessionRes.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 14: pb.LoginUserRes.user:type_name -> pb.UserRes
	16, // 15: pb.LoginUserRes.access_token_expires_at:type_name -> google.protobuf.Timestamp
	16, // 16: pb.LoginUserRes.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	16, // 17: pb.RenewAccessTokenRes.access_token_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 18: pb.Ecomm.CreateProduct:input_type -> pb.ProductReq
	0,  // 19: pb.Ecomm.GetProduct:input_type -> pb.ProductReq
	0,  // 20: pb.Ecomm.ListProducts:input_type -> pb.ProductReq
	0,  // 21: pb.Ecomm.UpdateProduct:input_type -> pb.ProductReq
	0,  // 22: pb.Ecomm.DeleteProduct:input_type -> pb.ProductReq
	4,  // 23: pb.Ecomm.CreateOrder:input_type -> pb.OrderReq
	4,  // 24: pb.Ecomm.GetOrder:input_type -> pb.OrderReq
	4,  // 25: pb.Ecomm.ListOrders:input_type -> pb.OrderReq
	4,  // 26: pb.Ecomm.DeleteOrder:input_type -> pb.OrderReq
	7,  // 27: pb.Ecomm.CreateUser:input_type -> pb.UserReq
	7,  // 28: pb.Ecomm.GetUser:input_type -> pb.UserReq
	7,  // 29: pb.Ecomm.ListUsers:input_type -> pb.UserReq
	7,  // 30: pb.Ecomm.UpdateUser:input_type -> pb.UserReq
	7,  // 31: pb.Ecomm.DeleteUser:input_type -> pb.UserReq
	10, // 32: pb.Ecomm.CreateSession:input_type -> pb.SessionReq
	10, // 33: pb.Ecomm.GetSession:input_type -> pb.SessionReq
	10, // 34: pb.Ecomm.RevokeSession:input_type -> pb.SessionReq
	10, // 35: pb.Ecomm.DeleteSession:input_type -> pb.SessionReq
	12, // 36: pb.Ecomm.LoginUser:input_type -> pb.LoginUserReq
	14, // 37: pb.Ecomm.RenewAccessToken:input_type -> pb.RenewAccessTokenReq
	1,  // 38: pb.Ecomm.CreateProduct:output_type -> pb.ProductRes
	1,  // 39: pb.Ecomm.GetProduct:output_type -> pb.ProductRes
	2,  // 40: pb.Ecomm.ListProducts:output_type -> pb.ListProductRes
	1,  // 41: pb.Ecomm.UpdateProduct:output_type -> pb.ProductRes
	1,  // 42: pb.Ecomm.DeleteProduct:output_type -> pb.ProductRes
	5,  // 43: pb.Ecomm.CreateOrder:output_type -> pb.OrderRes
	5,  // 44: pb.Ecomm.GetOrder:output_type -> pb.OrderRes
	6,  // 45: pb.Ecomm.ListOrders:output_type -> pb.ListOrderRes
	5,  // 46: pb.Ecomm.DeleteOrder:output_type -> pb.OrderRes
	8,  // 47: pb.Ecomm.CreateUser:output_type -> pb.UserRes
	8,  // 48: pb.Ecomm.GetUser:output_type -> pb.UserRes
	9,  // 49: pb.Ecomm.ListUsers:output_type -> pb.ListUserRes
	8,  // 50: pb.Ecomm.UpdateUser:output_type -> pb.UserRes
	8,  // 51: pb.Ecomm.DeleteUser:output_type -> pb.UserRes
	11, // 52: pb.Ecomm.CreateSession:output_type -> pb.SessionRes
	11, // 53: pb.Ecomm.GetSession:output_type -> pb.SessionRes
	11, // 54: pb.Ecomm.RevokeSession:output_type -> pb.SessionRes
	11, // 55: pb.Ecomm.DeleteSession:output_type -> pb.SessionRes
	13, // 56: pb.Ecomm.LoginUser:output_type -> pb.LoginUserRes
	15, // 57: pb.Ecomm.RenewAccessToken:output_type -> pb.RenewAccessTokenRes
	38, // [38:58] is the sub-list for method output_type
	18, // [18:38] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_grpc_pb_api_proto_init() }
func file_grpc_pb_api_proto_init() {
	if File_grpc_pb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_pb_api_proto_rawDesc), len(file_grpc_pb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_api_proto_goTypes,
		DependencyIndexes: file_grpc_pb_api_proto_depIdxs,
		MessageInfos:      file_grpc_pb_api_proto_msgTypes,
	}.Build()
	File_grpc_pb_api_proto = out.File
	file_grpc_pb_api_proto_goTypes = nil
	file_grpc_pb_api_proto_depIdxs = nil
}
