version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - noctx
    - rowserrcheck
    - sqlclosecheck

  exclusions:
    rules:
      - path: (_test\.go|test_helper\.go)$
        linters:
          - errcheck
          - noctx

formatters:
  enable:
    - gofmt
